version: '2'

services:

  web:
    build:
      context: web
      dockerfile: Dockerfile
    restart: "unless-stopped"
    container_name: web
    ports:
      - 443:443
    volumes:
      - /certs/staging:/certs/staging:ro

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped