version: '3.5'

services:

  web:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 443:443
    volumes:
      - /certs/staging:/certs/staging:ro

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: 'unless-stopped'
    # ports:
    #   - 8096:8096
    
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin